[package]
name = "toml-reds"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
red4ext-rs = { git = "https://github.com/jac3km4/red4ext-rs.git", rev = "v0.1.5" }
toml = "0.5"
static_init = "1"
